// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/2/2025, 10:47:04 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/plugins/**/*.{js,ts,mjs}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/composables/**/*.{js,ts,mjs}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/utils/**/*.{js,ts,mjs}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Argyn/Desktop/donpollo/Part2/donpollo/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;